'''
    PCHIP DISTRIBUTION (NON-PARAMETRIC DISTRIBUTION)
    =================================================================================
    The PCHIP distribution is a non-parametric distribution that is generated by 
    fitting piecewise hermite polynomials to the empirically-determined quantiles. 
    In other words, cubic spline interpolation.

    As long as the every data value is unique, a monotonic CDF will be constructed
    using PCHIP.

    
'''

import numpy as np
from scipy.interpolate import PchipInterpolator as sp_pchip
from math import ceil
from copy import deepcopy



'''
    SciPy-like class for PCHIP distribution.
'''
class pchip:

    name = 'pchip distribution'

    # Initialize 
    def __init__( self, cdf_pchip, interp_pts, interp_cdf ):
        self.cdf_pchip = cdf_pchip
        self.pdf_pchip = cdf_pchip.derivative(nu=1)
        self.interp_pts = interp_pts
        self.interp_cdf = interp_cdf
        return

    # Fit pchip distribution to data
    def fit( data1d, qtl_offset = 0.1, smooth_flag = True):

        # Generate empirical quantiles from sorted data
        sorted = np.sort( data1d )
        ndata = len(data1d)
        empirical_quantiles = np.linspace( 
            qtl_offset/ndata, 1-qtl_offset/ndata, ndata 
        )

        # Smooth data to limit jumps
        if smooth_flag and ndata > 10:
            for i in range( int(ndata**2/100) ):
                sorted[1:-1] = (
                    sorted[2:] + sorted[1:-1] + sorted[:-2]
                )/3

        # Generate CDF function
        cdf_pchip = sp_pchip( sorted, empirical_quantiles, extrapolate = False )

        # Generate stuff needed to approximate PPF
        interp_pts = np.linspace(sorted[0], sorted[-1], ndata*20)
        interp_cdf = cdf_pchip( interp_pts )

        return cdf_pchip, interp_pts, interp_cdf


    # Function to evaluate CDF of fitted pchip distribution. 
    def cdf(self, eval_pts):
        out_cdf = np.zeros_like( eval_pts )
        flag_eval = (self.interp_pts.min() <= eval_pts ) * ( eval_pts <= self.interp_pts.max() )
        out_cdf[flag_eval] = self.cdf_pchip(eval_pts[flag_eval])
        return out_cdf


    # Function to evaluate inverse CDF of fitted pchip
    def ppf(self, eval_cdf):
        return np.interp( eval_cdf, self.interp_cdf, self.interp_pts, left=None, right=None )
    

    # Function to evaluate PDF of fitted pchip
    def pdf( self, eval_pts ):
        return self.pdf_pchip(eval_pts, extrapolate = False)
        

    # Function to draw samples consistent with fitted pchip
    def rvs( self, shape ):
        rand = np.random.uniform( size = shape )
        return self.ppf_pchip( rand )
    
# ------ End of pchip distribution SciPy-like class







'''
    SANITY CHECK OF PCHIP DISTRIBUTION CLASS
'''
def SANITY_CHECK_pchip():

    import matplotlib.pyplot as plt
    from scipy.stats import norm

    # np.random.seed(0)

    # Data
    data = np.random.normal( size = 100)
    data -= np.mean(data)
    data /= np.std( data, ddof=1)

    # Fit
    params = pchip.fit( data )
    
    fitted_dist = pchip( *params )

    # Evaluate CDF, PPF & CDF for true distribution
    plot_coords = np.linspace( -4,4, 101 )
    true_cdf = norm.cdf( plot_coords )
    true_pdf = norm.pdf( plot_coords )
    true_pdf /= true_pdf.max()

    # Evaluate CDF, PPF & CDF for fitted distribution
    fit_cdf = fitted_dist.cdf( plot_coords )
    fit_ppf = fitted_dist.ppf( true_cdf )
    fit_pdf = fitted_dist.pdf( plot_coords ) 
    # fit_pdf /= fit_pdf[np.invert(np.isnan(fit_pdf))].max()

    # Plot out stuff!
    plt.plot( plot_coords, true_cdf, '-k', label = 'True CDF', linewidth=6)
    plt.plot( plot_coords, true_pdf, '--k', label = 'True Scaled PDF')
    plt.plot( plot_coords, fit_cdf, '-r', label = 'PCHIP CDF', linewidth=4)
    plt.plot( plot_coords, fit_pdf, '--r', label = 'PCHIP PDF')
    print( fit_pdf)
    plt.plot( fit_ppf, true_cdf, color='dodgerblue', label = 'PCHIP PPF', linewidth=2)
    plt.legend()
    plt.title( 'Std Norm vs PCHIP distribution')
    plt.savefig( 'SANITY_CHECK_pchip.pdf')


    



if __name__ == '__main__':

    SANITY_CHECK_pchip()