'''
    SCRIPT TO GENERATE modulated members VIA VERTICAL ENSEMBLE MODULATION
    ====================================================================
    Written by: Man-Yau (Joseph) Chan

    IMPORTANT: Only VERTICAL modulation is applied. Horizontal modulation is left to 
               another day...

    
    Description:
    ------------
        This MPI-enabled Python script applies VERTICAL ensemble modulation onto an ensemble
        of CAM model states to generate modulated members.

        The reference paper for ensemble modulation is:
            Bishop, C., & Hodyss, D. (2009). Ensemble covariances adaptively localized with 
            ECO-RAP. Part 2: A strategy for the atmosphere. Tellus A: Dynamic Meteorology 
            and Oceanography, 61(1), 97-111.
        
        The settings are defined in a file named config_pyPESE_CAM.py


    Assumption about CAM data:
    --------------------------
        All 1D variables and 0D variables are assumed to be the same across
        all ensemble members

        Time dimension is assumed to be singleton (i.e., only 1 time entry)
        

    Software requirements
    ---------------------
        1) Python packages: NumPy, SciPy, NetCDF4 and pyPESE

        2) Number of x-direction * y-direction grid cells does not exceed 
           maximum number of elements in a contiguous dimension of a NumPy 
           array. Typically less than 10^8 elements.     


    Data distribution across processes:
    -----------------------------------
        Data is divvied up among processes in two data layout modes.

        1) State-complete mode:
            Every process holds the entire model state for several ensemble
            members. To be clear, every member is assigned to only 1 process.

        2) Ensemble-complete mode:
            Every process holds a subset of the model state for all ensemble 
            members. To illustrate, suppose there are N original members, V virtual
            members and P processes. The model state is decomposed into P subsets. 
            Process 0 holds state subset 0 for all N+V members, process 1 holds state
            subset 1 for N+V members, and so forth.

        The conversion between data layout modes is called transposition.

        The state subsetting in ensemble-complete mode is generated by the following:
        a) Flatten the state variable array in the x & y directions (if relevant)
        b) Use MPI Scatter to scatter the flattened array across all processes.

        TODO: Use one-sided MPI communication via RMA to perform scattering instead
              of MPI Scatter. One-sided communication is ~40% more efficient than
              MPI scatter. See `compare_bcast_scatter_window.1node010proc.log` for
              comparison with 10 cores on a single node.
'''




'''
    IMPORT PYTHON PACKAGES
'''

# Import standard packages
import numpy as np
from sys import argv
from copy import deepcopy
from math import ceil as ceiling
from scipy.ndimage import convolve as scipy_convolve
import pickle
from os.path import isfile
from gc import collect as gc_collect
from shutil import copyfile as shutil_copyfile

# Import netCDF package
from netCDF4 import Dataset as ncopen

# Import useful parts of PyPESE package
from pyPESE.ensemble_modulation.ensemble_modulation import apply_ensemble_modulation
from pyPESE.balance_diagnosis.add_simple_cloud import add_cloud_to_camfile

# Import configurations
from config_pyPESE import ensemble_configuration as ens_config_dict, modulation_configuration as mdln_config_dict





''' 
    SET UP MPI4PY
'''
from mpi4py import MPI
from time import time

# CPU timer
t_start = time()

# Determine process id (aka rank) and total number of processes
comm = MPI.COMM_WORLD
my_proc_id = comm.Get_rank()
num_procs = comm.Get_size()

# Root process id is always zero.
root_proc_id = 0






'''
    USEFUL PRINT FUNCTION
'''
# Function to do collective printing (includes an MPI Barrier)
def collective_print( string, comm, root_proc_id = 0 ):

    if comm.rank == root_proc_id:
        print( '(%6.1f secs elapsed) ---- %s' % ( time()-t_start, string ) )
    
    comm.Barrier()

    return


msg = 'Initialized MPI with %d processes\n' % num_procs
collective_print( msg, comm )






'''
    ANOTHER USEFUL PRINT FUNCTION
    
    Note: No need to specify proc_id.
'''
def mpi_print( string, proc_id = my_proc_id ):

    print( 
        'Proc %4d (%6.1f secs elapsed) ---- %s'
        % (
            proc_id, time() - t_start, string
        ) 
    )
    
    return








'''
    PARSING ENSEMBLE CONFIGURATION
'''
collective_print( 'Parsing ensemble_configuration', comm)

# Ensemble sizes
fcst_ens_size = ens_config_dict['original ensemble size']
num_loc_dims = ens_config_dict['truncated localization dimension']
virt_ens_size = num_loc_dims * fcst_ens_size

# Generate paths to all original ensemble files
fcst_ens_fname_list = []
for imem in range(fcst_ens_size):

    # Construct file name for member imem
    fname = deepcopy(ens_config_dict['member file name template'])
    fname = fname.replace( 'MemberID', '%05d' % (imem+1))
    
    # Save file name
    fcst_ens_fname_list.append( fname )

# --- End of loop over ensemble members


# Generate paths to all modulation ensemble files
virt_ens_fname_list = {}
for imem in range(fcst_ens_size, fcst_ens_size+virt_ens_size):

    # Construct file name for member imem
    fname = deepcopy(ens_config_dict['member file name template'])
    fname = fname.replace( 'MemberID', '%05d_modulated' % (imem+1))
    
    # Save file name
    virt_ens_fname_list[imem] = fname

# --- End of loop over ensemble members



# SANITY CHECKS BASED ON PROVIDED ENSEMBLE INFORMATION
if (my_proc_id == root_proc_id):

    # Flag to abort program if conditions are not satisfied
    flag_abort = False

    # CHECK: Do all of the original forecast ensemble files exist?
    for imem, fname in enumerate(fcst_ens_fname_list):
        
        # Check if file even exists
        if not isfile( fname ):
            msg = 'ERROR: Original ensemble member file %s does not exist' % fname
            flag_abort = True        
    # --- End of sanity check

    # If any sanity check fails, abort program.
    if flag_abort:
        comm.Abort()
    # -- End of program abort trigger

# --- End of sanity checks performed by root process



# MPI Barrier to align processes
collective_print( 'Parsed ensemble_configuration\n', comm)








'''
    PARSING ENSEMBLE MODULATION CONFIGURATIONS
'''
# Number of variables to apply ensemble modulation on
num_vrbl = len( mdln_config_dict.keys() )

# List of modulation matrix files
mdln_matrix_pkl_flist = []
for vname in mdln_config_dict.keys():
    fname = deepcopy(mdln_config_dict[vname]['modulation matrix file'])
    if fname not in mdln_matrix_pkl_flist:
        mdln_matrix_pkl_flist.append( fname )









'''
    LOAD SQUARE-ROOT OF LOCALIZATION MATRICES INTO ROOT PROCESS
'''
collective_print( 'Loading localization square-root matrix into root process', comm)

# Init dict
sqrt_matrix_dict = {}

# Loop over files
for fname in mdln_matrix_pkl_flist:

    # Load data
    with open( fname, 'rb') as f:
        sqrt_matrix_dict[fname] = pickle.load( f )
    # --- End of data loading

    # Check truncation matching
    for pname in ['pres_mass_sqrt_loc', 'pres_stag_sqrt_loc']:
        shp = sqrt_matrix_dict[fname][pname].shape
        if ( num_loc_dims != shp[1] ):
            mpi_print(f'ERROR:  num_loc_dims ({num_loc_dims}) does not match provided sqrt matrix')
            mpi_print(f'    Matrix info: {fname}, {pname}')
            MPI.Abort()

# --- End of loop over all sqrt matrix files



collective_print( 'Loaded localization square-root matrix into root process\n', comm)













'''
    DETERMINE PRESSURE LEVEL INDEX CLOSEST TO SURFACE LEVEL
'''
collective_print( 'Determining array index corresponding to bottommost level', comm)
plvls = sqrt_matrix_dict[fname]['pres_stag']
if plvls[0] > plvls[-1]:
    surf_lvl_index = 0
elif plvls[-1] > plvls[0]:
    surf_lvl_index = -1

collective_print( f'Pressure at lvl 0 & -1: {plvls[0]}, {plvls[-1]}', comm)
collective_print( f'Chosen lvl to represent horizontal quantities: {surf_lvl_index}', comm)


collective_print( 'Finished determining array index corresponding to bottommost level\n', comm)







'''
    GENERATE ENSEMBLE-COMPLETE MEMORY LAYOUT INFO
'''


collective_print( 'Determining grid decomposition for transposition to ensemble-complete mode', comm)


# Init variable
nz_stag     = None
nlat_stag   = None
nlon        = None
num_noise   = None



# Pass information about staggered grid dims to all processes
# -----------------------------------------------------------

# Extract dim info from a noise file in root proc
if my_proc_id == root_proc_id:

    # Arbitrary noise file name
    fname = mdln_matrix_pkl_flist[0]

    # Load info!
    nz_stag     = sqrt_matrix_dict[fname]['nz_stag']
    nlat_stag   = sqrt_matrix_dict[fname]['nlat']
    nlon        = sqrt_matrix_dict[fname]['nlon']
    # num_noise   = sqrt_matrix_dict[fname]['global grid noise samples'].shape[0]

# --- end of instructions for root proc


# Broadcast dimension information to all processes
nz_stag     = comm.bcast(   nz_stag, root = root_proc_id )
nlat_stag   = comm.bcast(   nlat_stag, root = root_proc_id )
nlon        = comm.bcast(   nlon, root = root_proc_id )
# num_noise   = comm.bcast( num_noise, root = root_proc_id )


# Write dictionary for easy access to coordinates
dim_dict = {
    'lat': nlat_stag,
    'slat': nlat_stag-1,
    'lon': nlon,
    'slon': nlon,
    'ilev': nz_stag,
    'lev': nz_stag-1
}


# Dictionaries for state layout
all_procs_xy_ind_dict = {}
my_xy_ind_dict = {}
for dict_nw in [my_xy_ind_dict, all_procs_xy_ind_dict]:
    for gridtype in ['mass','u_stag','v_stag']:
        dict_nw[gridtype] = {}


# Set up grid information
for dict_nw in [my_xy_ind_dict, all_procs_xy_ind_dict]:
    dict_nw['mass']['grid-complete xy dims']   = ['lat','lon']
    dict_nw['u_stag']['grid-complete xy dims'] = [ 'lat','slon' ]
    dict_nw['v_stag']['grid-complete xy dims'] = [ 'slat','lon']


# Generate ensemble-complete layouts
for gridtype in ['mass','u_stag','v_stag']:

    # Parse dimensions
    ykey, xkey = dict_nw[gridtype]['grid-complete xy dims'][:]
    y_dim = dim_dict[ykey]
    x_dim = dim_dict[xkey]

    # Generate indices defining grid columns
    ymesh, xmesh = np.mgrid[0:y_dim, 0:x_dim]
    ylist = ymesh.flatten()
    xlist = xmesh.flatten()

    # Split grid locations among procs
    all_procs_xy_ind_dict[gridtype]['y inds'] = np.array_split( ylist, num_procs )
    all_procs_xy_ind_dict[gridtype]['x inds'] = np.array_split( xlist, num_procs )

    # Current process' index
    my_xy_ind_dict[gridtype]['y inds'] = all_procs_xy_ind_dict[gridtype]['y inds'][my_proc_id]
    my_xy_ind_dict[gridtype]['x inds'] = all_procs_xy_ind_dict[gridtype]['x inds'][my_proc_id]
    my_xy_ind_dict[gridtype]['len'] = len( my_xy_ind_dict[gridtype]['x inds'] )

# --- end of loop over grid types



collective_print( 'Finished determining grid decomposition for transposition to ensemble-complete mode.\n', comm)


# Handy dictionary for identifying horizontal grid types
iden_gtype = {}
iden_gtype[ ('lat', 'lon') ] = 'mass'
iden_gtype[ ('lat', 'slon') ] = 'u_stag'
iden_gtype[ ('slat', 'lon') ] = 'v_stag'






















'''
    DETERMINE WHICH PROCESS HOLDS WHICH MEMBERS' GRID-COMPLETE DATA
'''

collective_print( 'Determining which process handles which ensemble member', comm)
# Determine fcst members that each process is in charge of during "grid-complete" mode
fcst_imem_allotment_for_all_procs = []

# This loop handles situation where num_procs > fcst_ens_size
for iproc in range( num_procs ):
    if ( iproc < fcst_ens_size ):
        fcst_imem_allotment_for_all_procs.append( 
            np.arange(fcst_ens_size)[iproc::num_procs]
        )
    else:
        fcst_imem_allotment_for_all_procs.append( None )


# Determine modulated members that each process is in charge of during "grid-complete" mode
virt_imem_allotment_for_all_procs = []

# This loop handles situation where num_procs > virt_ens_size
for iproc in range( num_procs ):
    if ( iproc < virt_ens_size ):
        virt_imem_allotment_for_all_procs.append( 
            np.arange(virt_ens_size)[iproc::num_procs] + fcst_ens_size
        )
    else:
        virt_imem_allotment_for_all_procs.append( None )


# Determine this process' member allotment
my_fcst_imem_allotment = fcst_imem_allotment_for_all_procs[my_proc_id]
my_virt_imem_allotment = virt_imem_allotment_for_all_procs[my_proc_id]



# Important note: 
# Process 0 is guaranteed to have at least one grid-complete forecast member and
# one grid-complete modulated member associated with it. 

collective_print( 'Finished determining which process reads/writes which ensemble member\n', comm)

























'''
    LOAD ORIGINAL ENSEMBLE IN GRID-COMPLETE FORM
'''

collective_print( 'Loading original CAM ensemble in grid-complete form\n', comm)

my_grid_complete_fcst_dict = {}

# Generate variable handle for original ensemble members alloted to this process
if my_fcst_imem_allotment is not None:
    for imem in my_fcst_imem_allotment:

        # Generate file handle
        f = ncopen( fcst_ens_fname_list[imem], 'r' )

        # Init sub-dictionary to hold all data
        my_grid_complete_fcst_dict[imem] = {}
        my_grid_complete_fcst_dict[imem]['variables'] = {}

        # Load all variables
        for vname in f.variables.keys():

            # Generate dictionary to hold grid-complete variable data, attributes and dimensions
            my_grid_complete_fcst_dict[imem]['variables'][vname] = {}
            my_grid_complete_fcst_dict[imem]['variables'][vname]['attributes'] = deepcopy(
                f.variables[vname].__dict__
            )
            my_grid_complete_fcst_dict[imem]['variables'][vname]['dimensions'] = deepcopy(
                f.variables[vname].dimensions[1:]
            )
            my_grid_complete_fcst_dict[imem]['variables'][vname]['data'] = np.squeeze(
                f.variables[vname]
            )

            # Reading in description of the variable
            attributes_string = ''
            for keyname in my_grid_complete_fcst_dict[imem]['variables'][vname]['attributes'].keys():
                attributes_string += " " + my_grid_complete_fcst_dict[imem]['variables'][vname]['attributes'][keyname]

            # # Zero'ing out small mass mixing ratios and humidities (only applying to GC)
            # if ens_config_dict['resampling mode'].upper() == 'GC':
            #     if 'MIXING RATIO' in attributes_string.upper() or 'HUMIDITY' in attributes_string.upper():
            #         zeroing_flags = my_grid_complete_fcst_dict[imem]['variables'][vname]['data'] < 1e-5
            #         zeroing_flags *= ( my_grid_complete_fcst_dict[imem]['variables'][vname]['data'] > 0 )
            #         num_neglig = np.sum( zeroing_flags )
            #         if num_neglig > 0:
            #             msg = 'Zeroing out negligible positive %s values at %d grid boxes' % (vname, num_neglig)
            #             mpi_print(msg)
            #             my_grid_complete_fcst_dict[imem]['variables'][vname]['data'][zeroing_flags] = 0
        
        # Load all global attributes
        my_grid_complete_fcst_dict[imem]['attributes'] = deepcopy( f.__dict__ )
        
        
        # Close file
        f.close()


    # --- End of loop over this process' original members
# --- End of checking whether original member(s) are alloted to this process



# Precautionary memory purge
gc_collect()


collective_print( 'Finished loading original CAM ensemble in grid-complete form.\n', comm)





















'''
    GENERATE ENSEMBLE-COMPLETE DATA ON ALL PROCESSES
        This is an MPI-heavy process.
        CAM data transposition only applies to variables with 2 or more spatial dimensions.
'''

collective_print( 'Copying original CAM ensemble into grid-decomposed ensemble-complete form.', comm)


data_info_dict = None

# Root process identify grid types for all loaded CAM variables
# -------------------------------------------------------------
if my_proc_id == root_proc_id:

    # Dictionary to hold data dimensions
    data_info_dict = {}

    # Loop over all available variables
    for vname in my_grid_complete_fcst_dict[imem]['variables'].keys():
        data_info_dict[vname] = {}
        data_info_dict[vname]['shape'] = ( my_grid_complete_fcst_dict[imem]['variables'][vname]['data'] ).shape
        data_info_dict[vname]['dtype'] = ( my_grid_complete_fcst_dict[imem]['variables'][vname]['data'] ).dtype
        data_info_dict[vname]['dimensions'] = deepcopy( my_grid_complete_fcst_dict[imem]['variables'][vname]['dimensions'] )
    # --- End of loop
# --- End of root process instruction


# Broadcast dictionary of dimensions
data_info_dict = comm.bcast( data_info_dict, root = root_proc_id)

collective_print( '    All procs received info on data dims.', comm)




collective_print( '    Initializing arrays to hold ens-complete data.', comm)
# Init arrays to hold ensemble complete data
my_ens_complete_data = {}
for vname in data_info_dict.keys():

    msg = '        Prepping ensemble-complete array for %s ...' % vname
    collective_print( msg, comm)

    msg = '        ... detected data shape: %s' % ( str(data_info_dict[vname]['shape']) )
    collective_print( msg, comm)

    # Ignore all variables that have 0 or 1 spatial dimensions
    if len( data_info_dict[vname]['shape'] ) <= 1:
        msg = '        ... skipping %s bcos have less than 2 dims.' % vname
        collective_print( msg, comm)
        continue
    
    # Detect horizontal grid type
    shp_last2 = data_info_dict[vname]['dimensions'][-2:]
    gtype = iden_gtype[shp_last2]
    msg = '        ... detected grid type is %s' % gtype
    collective_print( msg, comm)

    # Init array to hold transposed data with 2 spatial dimensions
    if len( data_info_dict[vname]['shape'] ) == 2:
        my_ens_complete_data[vname] = np.empty(
            [ fcst_ens_size + virt_ens_size, my_xy_ind_dict[gtype]['len'] ], 
            dtype = data_info_dict[vname]['dtype']
        )
    
    # Init array to hold transposed data with 3 spatial dimensions
    if len( data_info_dict[vname]['shape'] ) == 3:
        my_ens_complete_data[vname] = np.empty(
            [ fcst_ens_size + virt_ens_size,  
              data_info_dict[vname]['shape'][0], 
              my_xy_ind_dict[gtype]['len'] 
            ], 
            dtype = data_info_dict[vname]['dtype']
        )

    # Sanity checking if array is allocated
    if vname in my_ens_complete_data.keys():
        msg = '        ... successfully allocated %s ensemble-complete array for %s' % (
            str(my_ens_complete_data[vname].shape), vname
        )
        collective_print( msg, comm)
    else:
        msg = '        ... ERROR: failed to allocate ensemble-complete array for %s' % vname
        collective_print( msg, comm)
        comm.Abort()

# --- End of array initialization

collective_print( '     ', comm)





bufr = None
collective_print( '    Transposing CAM data from grid complete to ensemble complete.', comm)

# Pass original ensemble information, one process & variable at a time
for iv, vname in enumerate(data_info_dict.keys()):

    msg = '        Transposing variable %s into ensemble-complete form' % (vname)
    collective_print( msg, comm)

    # Only scatter if have 2 or more spatial dimensions
    if len( data_info_dict[vname]['shape'] ) <= 1:
        msg = '        ... skipping %s bcos have less than 2 dims.' % vname
        collective_print( msg, comm)
        continue
    
    # Detect horizontal grid type
    shp_last2 = data_info_dict[vname]['dimensions'][-2:]
    gtype = iden_gtype[shp_last2]

    # Loop over all processes
    for iproc in np.arange(num_procs):

        # Skip if this process does not contain an original member
        if fcst_imem_allotment_for_all_procs[iproc] is None:
            comm.Barrier()
            continue

        # Loop over members held by process iproc
        for imem in fcst_imem_allotment_for_all_procs[iproc]:

            # Process iproc preps data for scattering
            if my_proc_id == iproc:

                # Prep to handle data
                tmp = deepcopy( my_grid_complete_fcst_dict[imem]['variables'][vname]['data'] )

                # Two spatial dimension scenario
                if len( data_info_dict[vname]['shape'] ) == 2: 
                    tmp = tmp.reshape( 
                        dim_dict[my_xy_ind_dict[gtype]['grid-complete xy dims'][0]] 
                        * dim_dict[my_xy_ind_dict[gtype]['grid-complete xy dims'][1]] )
                    bufr = np.array_split( tmp, num_procs ) 
                    
                # Three spatial dimension scenario
                elif len( data_info_dict[vname]['shape'] ) == 3: 
                    tmp = tmp.reshape( 
                        [   data_info_dict[vname]['shape'][0], 
                            dim_dict[my_xy_ind_dict[gtype]['grid-complete xy dims'][0]] 
                            * dim_dict[my_xy_ind_dict[gtype]['grid-complete xy dims'][1]]
                        ])
                    tmp = tmp.T
                    bufr = np.array_split( tmp, num_procs, axis=0 ) 
                
                else:
                    bufr = -999
                
            # --- End of instruction for root process

            # Scatter buffer
            tmp = ( comm.scatter(bufr, root = iproc) ).T
            # if vname == 'PB':
            #     msg = '    Scattered buffer dimensions: %s ' % (str(tmp.shape))
            #     msg += '  Receiver shape: %s' % (str(my_ens_complete_data[vname][imem].shape))
            #     mpi_print(msg)
            my_ens_complete_data[vname][imem]  = tmp

            # Free up memory every so often
            if (iv % 5 == 0):
                gc_collect()

            # Align processes
            comm.Barrier()


        # --- End of loop over original members held by process iproc
    # --- End of loop over all processes
# --- End of loop over CAM variables

collective_print( 'Finished copying original CAM ensemble into grid-decomposed ensemble-complete form.\n', comm)














'''
    SEPARATING VARIABLES INTO MEMBER-VARYING & MEMBER-INVARIANT (CONST)
'''

collective_print( 'Separating variables into member-varying & member-invariant.', comm)

# Determine all CAM variables' names in ens-complete data
ens_complete_vname_list = list( my_ens_complete_data.keys() )

# Init lists to hold names of member-invariant fields and member-varying fields
ens_complete_const_list = []
ens_complete_vary_list = []

# Separating variables into variant and invariant fields
for vname in ens_complete_vname_list:

    msg = '    Looking into variable %s' % vname
    collective_print( msg, comm )

    # Determine ensemble range
    minval = np.amin( my_ens_complete_data[vname][:fcst_ens_size], axis=0)
    maxval = np.amax( my_ens_complete_data[vname][:fcst_ens_size], axis=0)
    # min_isinvalid = ( np.isnan(minval) + np.isinf(minval) ) > 0
    # max_isinvalid = ( np.isnan(maxval) + np.isinf(maxval) ) > 0
    # msg = 'Invalid values in min: %d. Invalid values in max: %d, data_dim %s ' % (
    #     np.sum(min_isinvalid), np.sum(max_isinvalid), str( my_ens_complete_data[vname].shape )
    # )
    # mpi_print(msg)
    # comm.Barrier()
    # comm.Abort()
    maxin_range = maxval - minval

    # Is this a member-varing or member-invariant field?
    if np.sum( maxin_range > 0 ) == 0:
        flag_const = True
    else:
        flag_const = False

    # Do all processes concur that this field is invariant?
    flag_const_list = comm.allgather( flag_const )
    flag_const_final = np.sum( flag_const_list ) == num_procs
    if flag_const_final:
        msg = '        ... treating as a member-INVARIANT field'
        collective_print( msg, comm)
        ens_complete_const_list.append(vname)

    # Is this variable member-varying and found in config_pyPESE_CAM?
    elif vname in mdln_config_dict.keys():
        msg = '        ... treating as a member-VARYING field'
        collective_print( msg, comm)
        ens_complete_vary_list.append(vname)

    # All other cases
    else:
        msg = '        ... this a member-varying field that is not specified in config_pyPESE_CAM.py'
        collective_print( msg, comm)
        msg = '        ... ignoring this field.'
        collective_print( msg, comm)
    # --- End of checks

# --- End of loop over all variables


collective_print( 'Finished separating variables into member-varying & member-invariant.\n', comm)













            














'''
    APPLY ENSEMBLE MODULATION ON ENSEMBLE-COMPLETE DATA
    This is an embarrassingly parallel process

    Note: Only vertical localization is supported here. 
'''
collective_print('Applying VERTICAL ensemble modulation.', comm)

# Looping over variables
for vname in my_ens_complete_data.keys():

    # Skipping over invariants
    if vname not in ens_complete_vary_list:
        continue

    collective_print( f"    Processing {vname}", comm)

    # sqrt matrix file name
    sqrt_fname = mdln_config_dict[vname]['modulation matrix file']

    # Checking for vertical grid type
    datadims = my_ens_complete_data[vname].shape
    if( len(datadims) == 2 ):
        sqrt_matrix = (sqrt_matrix_dict[sqrt_fname]['pres_stag_sqrt_loc'][surf_lvl_index,:]*1)[np.newaxis,:]
        # surf_lvl_index is defined around line 320
    elif ( len(datadims) == 3 ):
        if data_info_dict[vname]['shape'][0] == dim_dict['ilev']:
            sqrt_matrix = sqrt_matrix_dict[sqrt_fname]['pres_stag_sqrt_loc']*1
        elif data_info_dict[vname]['shape'][0] == dim_dict['lev']:
            sqrt_matrix = sqrt_matrix_dict[sqrt_fname]['pres_mass_sqrt_loc']*1
    else:
        mpi_print( f'ERROR: datadims is neither 2D nor 3D ({datadims})')
        MPI.Abort()

    collective_print( f"    {vname} dimensions identified", comm)

        
    # Apply modulation onto 2D case...
    if( len(datadims) == 2 ):
        for iloc in range( datadims[-1] ):
            mdl_members = apply_ensemble_modulation( 
                sqrt_matrix, my_ens_complete_data[vname][:fcst_ens_size,iloc][np.newaxis,:]
            )
            my_ens_complete_data[vname][fcst_ens_size:,iloc] = mdl_members[0,:]

    # Apply modulation onto 3D case....
    if( len(datadims) == 3 ):
        for iloc in range( datadims[-1] ):
            mdl_members = apply_ensemble_modulation( 
                sqrt_matrix, my_ens_complete_data[vname][:fcst_ens_size,:,iloc].T
            )
            my_ens_complete_data[vname][fcst_ens_size:,:,iloc] = mdl_members.T
    
                                
    # Handling negative Q values by zeroing them, then rescale to match the old mean.
    if vname == 'Q':

        # Accessing each geographical location
        for iloc in range( datadims[-1] ):
            mdl_members2d = my_ens_complete_data[vname][fcst_ens_size:,:,iloc]

            # Handling negative Q removal on a level-by-level basis
            for ilvl in range( dim_dict['lev'] ):

                # Modify ensemble
                virt_ens1d = mdl_members2d[:,ilvl]*1
                mean_old = np.mean( virt_ens1d )
                virt_ens1d_new = deepcopy( virt_ens1d  )
                virt_ens1d_new[virt_ens1d < 0] = 0
                mean_new = np.mean(virt_ens1d_new)
                rescale = mean_old/mean_new
                virt_ens1d = virt_ens1d_new * rescale

                # Pass modified ensemble back to ensembel complete mode
                my_ens_complete_data[vname][fcst_ens_size:,ilvl,iloc] = virt_ens1d

    # ------- End of negative Q handling

# --- End of loop over variable names
                        

collective_print('Finished applying VERTICAL ensemble modulation.\n', comm)





















'''
    TRANSPOSE MEMBERS FROM ENSEMBLE-COMPLETE TO GRID-COMPLETE MODE

    Note: Root process always carries at least one forecast member
'''
collective_print('Transposing modulated members from ensemble-complete to grid-complete.', comm)


collective_print('    Initializing dictionary to hold modulated member data', comm)
# Generate dictionary to hold grid-complete member-varying data arrays
# --------------------------------------------------------------------
my_grid_complete_virt_dict = {}
if my_virt_imem_allotment is not None:
    for imem in my_virt_imem_allotment:
        my_grid_complete_virt_dict[imem] = {}
        my_grid_complete_virt_dict[imem]['variables'] = {}
        for vname in ens_complete_vary_list:
            my_grid_complete_virt_dict[imem]['variables'][vname] = {}
            my_grid_complete_virt_dict[imem]['variables'][vname]['data'] = np.zeros(
                data_info_dict[vname]['shape'], dtype = data_info_dict[vname]['dtype']
            )


collective_print('    Obtaining attribute information for member-varying variables from root process', comm)
# Obtain attribute information from root process
# -----------------------------------------------
for vname in ens_complete_vary_list:

    # Obtain attribute info
    tmp = None
    if my_proc_id == root_proc_id:
        tmp = my_grid_complete_fcst_dict[0]['variables'][vname]['attributes']
    meta = comm.bcast( tmp, root = 0)

    # Put into dictionary
    if my_virt_imem_allotment is not None:
        for imem in my_virt_imem_allotment:
            my_grid_complete_virt_dict[imem]['variables'][vname]['attributes'] = deepcopy(meta)
# --- End of attribute obtainment process


collective_print('    Obtaining member-invariant fields from root process', comm)
# Obtain member-invariant fields from root process
# ------------------------------------------------
for vname in ens_complete_const_list:

    # Obtain data
    tmp = None
    if my_proc_id == root_proc_id:
        tmp = my_grid_complete_fcst_dict[0]['variables'][vname]
    data_arr_and_att = comm.bcast( tmp, root=0 )

    # Shove into dictionary
    if my_virt_imem_allotment is not None:
        for imem in my_virt_imem_allotment:
            my_grid_complete_virt_dict[imem]['variables'][vname] = data_arr_and_att
# End of obtaining invariant fields



collective_print('    Gathering member-varying data', comm)
# Collect member-varying data for modulated members
# -----------------------------------------------
# This MPI gather is done variable & member at a time to limit buffer sizes
# b'cos large buffers take time to allocate.
# Note, to reduce process downtime, will gather all data first to the relevant processes first,
# then remap the gathered data into the regular grid.
# In contrast, doing both the gathering & remapping together results in idling processes.

# Init dictionary to hold gathered data
gather_buf_dict = {}
for vname in ens_complete_vary_list:
    gather_buf_dict[vname] = {}
    

# Loop over all modulated members & variables (this takes three nested loops: vname, iproc & imem)
for vname in ens_complete_vary_list:

    msg = '        ... gathering %s' % (vname)
    collective_print(msg, comm)

    for iproc in np.arange(num_procs):
        
        # Skip if process iproc is not alloted any grid-complete modulated members
        if virt_imem_allotment_for_all_procs[iproc] is None:
            comm.Barrier()
            continue      

        # Loop over modulated members alloted to process iproc
        for imem in virt_imem_allotment_for_all_procs[iproc]:

            # MPI-gather the data to the process iproc
            buf = np.squeeze(my_ens_complete_data[vname][imem])
            gathered_buf = comm.gather( buf, root = iproc )
            # Note: The gathered_buf variable is a list containing domain fragments

            # SAFETY MEASURE: Gather process ids as well
            gathered_proc_ids = comm.gather( my_proc_id, root = iproc)

            # Chuck gathered data & process ids into an easy-to-access dictionary
            if my_proc_id == iproc:
                gather_buf_dict[vname][imem] = {}
                gather_buf_dict[vname][imem]['data'] = gathered_buf
                gather_buf_dict[vname][imem]['proc ids'] = gathered_proc_ids
            # --- End of instruction for iproc

            # Synchronize procs
            comm.Barrier()
        
        # --- End of loop over modulated members allotted to proc iproc

        # Garbage collection to prevent memory overuse due to allocation of buffers
        if iproc % 5 == 0 and iproc > 0:
            gc_collect()


    # --- End of loop over active processes
# --- End of loop over variable naems


# Destroy ensemble complete data to reduce memory use
msg = '    Freeing up memory by deleting ensemble-complete data structures'
collective_print( msg, comm )
del my_ens_complete_data
gc_collect()


# Every modulated member-holding process rearranges data into CAM's grids
collective_print('    Rearranging data fragments into CAM grids', comm)
if my_virt_imem_allotment is not None:
    for imem in my_virt_imem_allotment:
        for vname in ens_complete_vary_list:

            # Detect horizontal grid type
            shp_last2 = data_info_dict[vname]['dimensions'][-2:]
            gtype = iden_gtype[ shp_last2 ]

            # Loop over received fragments
            for ifrag in range(num_procs):

                # Select data fragment & determine grid indices
                iproc = gather_buf_dict[vname][imem]['proc ids'][ifrag]
                data_arr = gather_buf_dict[vname][imem]['data'][ifrag]
                x_inds = all_procs_xy_ind_dict[gtype]['x inds'][iproc]
                y_inds = all_procs_xy_ind_dict[gtype]['y inds'][iproc]

                # Handling 2D situation
                if len( data_info_dict[vname]['shape']) == 2:
                    my_grid_complete_virt_dict[imem]['variables'][vname]['data'][y_inds, x_inds] = data_arr
                
                # Handling 3D situation
                elif len( data_info_dict[vname]['shape']) == 3:
                    my_grid_complete_virt_dict[imem]['variables'][vname]['data'][:, y_inds, x_inds] = data_arr
                
                else:
                    msg = 'ERROR: received modulated member %d data variable %s is neither 2D nor 3D. Exiting.' % (imem+1, vname)
                    mpi_print(msg)
                    comm.Abort()
                # --- End of handling data dimensions
            
            # --- End of loop over received fragments
        # --- End of loop over variables
    # --- End of loop over modulated members alloted to this process
# --- End of escape condition for processes that are not holding onto data

# Reducing memory overhead
msg = '    Freeing up memory by deleting list of data fragments'
collective_print( msg, comm )
del gather_buf_dict
gc_collect()


# Obtain file attributes from root process
# ----------------------------------------
collective_print('    Obtaining netCDF file attributes from root process', comm)
tmp = None
if my_proc_id == root_proc_id:
    tmp = my_grid_complete_fcst_dict[0]['attributes']
ncf_attrs = comm.bcast( tmp, root = root_proc_id )


collective_print('Finished transposing modulated members from ensemble-complete to grid-complete.\n', comm)








'''
    CLEANING UP MEMORY USAGE IN PREPARATION FOR IMPOSING CONSTRAINTS (QUITE MEMORY HEAVY)
'''
collective_print('Cleaning up memory usage', comm)
del my_grid_complete_fcst_dict
# del my_sqrt_matrix_dict
gc_collect()
collective_print('Finished cleaning up memory usage.\n', comm)























'''
    WRITE modulated members TO FILE

    Had some help from ChatGPT for this to save time.
    https://chatgpt.com/share/683f78f3-1628-8008-bb5d-920a226c3815
'''
collective_print('Writing modulated members to file.', comm)

# Ignore processes that have no modulated members allocated
if my_virt_imem_allotment is not None:

    # Open a forecast member file for reference
    tmp = iproc % fcst_ens_size
    fcst_ncfile = ncopen( fcst_ens_fname_list[tmp], 'r')

    # Loop over modulated members alloted to process
    for imem in my_virt_imem_allotment:

        # Load output file name
        out_fname = virt_ens_fname_list[imem]

        # Open modulated member file
        virt_ncfile = ncopen( out_fname, 'w')

        # Copy global attributes
        virt_ncfile.setncatts({attr: fcst_ncfile.getncattr(attr) for attr in fcst_ncfile.ncattrs()})

        # Copy dimensions
        for name, dimension in fcst_ncfile.dimensions.items():
            virt_ncfile.createDimension(name, (len(dimension) if not dimension.isunlimited() else None))

        # Generate variable with good attribute and inject modulated member array
        for name, variable in fcst_ncfile.variables.items():

            # Handling member-varying field
            if name in ens_complete_vary_list:
                x = virt_ncfile.createVariable(name, variable.datatype, variable.dimensions)
                virt_ncfile[name][0,:] = my_grid_complete_virt_dict[imem]['variables'][name]['data']
                x.setncatts({k: variable.getncattr(k) for k in variable.ncattrs()})

            # Handling member-invariant field
            else: #if name in ens_complete_const_list:
                x = virt_ncfile.createVariable(name, variable.datatype, variable.dimensions)
                virt_ncfile[name][:] = fcst_ncfile[name][:]
                x.setncatts({k: variable.getncattr(k) for k in variable.ncattrs()})
            
        # --- End of loop over variables

        # Add cloud to CAM file
        add_cloud_to_camfile( virt_ncfile )

        # Close relevant netCDF file
        virt_ncfile.close()
    # --- End of loop over members

    fcst_ncfile.close()
# --- End of instruction for virtual-member-bearing processes


collective_print('Finished writing modulated members to file.\n', comm)









'''
    TERMINATING PROGRAM
'''
msg = 'SUCCESS -- CAM-EnsembleModulation ran to completion. Exiting program.'
collective_print(msg, comm)
MPI.Finalize()